# Yarn Berry 설정
# pnp 일 때는 enableGlobalCache 를 true 로 설정해야 함
nodeLinker: pnp
enableGlobalCache: true
# node-modules 일 때는 enableGlobalCache 를 false 로 설정해야 함
# nodeLinker: node-modules
# enableGlobalCache: false
yarnPath: .yarn/releases/yarn-4.9.2.cjs

# 캐시 설정
compressionLevel: mixed
